/**
 * The palette as literal values, for the places that have no stylesheet.
 *
 * Most of the app reads colour through `var(--navy)` and friends, which `globals.css` defines on
 * `:root`. Three things this app produces never see that file:
 *
 *   - **the OG image** (`app/bid/[token]/og/route.tsx`) — Satori rasterises a tree of inline styles
 *     with no document and no cascade, so a custom property resolves to nothing
 *   - **the clipboard card** (`bidCardHtml.ts`) — pasted into Gmail, Outlook or Word, which supply
 *     their own document and none of ours
 *   - **the quotation** (`quotation/render.ts`) — a standalone HTML file that is printed or saved
 *
 * The first two need literals. The third builds its own document, so it takes `DS_ROOT_CSS` and
 * keeps writing `var(--navy)` like every other surface.
 *
 * ── This file and globals.css must agree ────────────────────────────────────────────────────────
 * They hold the same numbers twice, which is a thing worth being nervous about. `ds-colors.test.ts`
 * parses `globals.css` and fails if any value here has drifted from it, so the duplication cannot
 * quietly rot — change one and the test names the other.
 */

export const COLORS = {
  // Generated from `globals.css` :root, in its own order — the palette is the SUPPLIER OS set
  // (owner, 2026-09-04; `docs/design-tokens.md`). `ds-colors.test.ts` fails the moment the two
  // disagree, which is the only reason this duplication is allowed to exist.
  navyDeep: "#1c2738",
  navy: "#22384e",
  navyMid: "#33506d",
  mutedDark: "#444f57",
  muted: "#59646e",
  mutedLight: "#8a95a0",
  borderStrong: "#c6c6c6",
  border: "#dcdcdc",
  surface3: "#e8e8e8",
  surface2: "#f4f4f4",
  background: "#f4f4f4",
  surface: "#ffffff",
  foreground: "#22384e",
  ink: "#22384e",
  inkDeep: "#1c2738",
  navySoft: "#33506d",
  textPrimary: "#22384e",
  textSecondary: "#444f57",
  textTertiary: "#515a64",
  textMuted: "#59646e",
  textFaint: "#6f695a",
  textOnDark: "#c8d4e4",
  textOnDarkDim: "#8698b0",
  desktopBase: "#f4f4f4",
  desktopHi: "#ffffff",
  surfaceRaised: "#ffffff",
  surfaceAlt: "#fafafa",
  chrome: "#f4f4f4",
  chromePress: "#e8e8e8",
  chromeDeep: "#e0e0e0",
  neutralBtn: "#e0e0e0",
  neutralBtnHi: "#d4d4d4",
  mapPlate: "#dfe3e7",
  borderMid: "#d0d0d0",
  borderHair: "#e4e4e4",
  borderHair2: "#e0e0e0",
  brand: "#f97316",
  brandDeep: "#c2570f",
  brandHover: "#db6513",
  brandPress: "#bd5711",
  brandLight: "#e8b64c",
  brandPale: "#fee0cc",
  brandSoft: "#fef1e8",
  brandFg: "#ffffff",
  gold: "#b8860b",
  ok: "#1d9e55",
  okSoft: "#e2efe7",
  okDeep: "#1d7a45",
  warn: "#b98a1d",
  warnSoft: "#f7edd8",
  warnDeep: "#8a6412",
  warnBorder: "#e0c583",
  warnAmber: "#e8b64c",
  danger: "#c02626",
  dangerSoft: "#f7e3e3",
  dangerDeep: "#b91c1c",
  dangerBorder: "#e8c1c1",
  dangerWash: "#fbeeee",
  dangerHover: "#a92121",
  dangerPress: "#921d1d",
  action: "#1a7ec8",
  info: "#3b556e",
  infoSoft: "#e7ebee",
  infoDeep: "#22384e",
  ai: "#6d4fc4",
  aiBg: "#eee9fa",
  neutral: "#8a95a0",
  neutralBg: "#eceae3",
  stIdle: "#b98a1d",
  stReserved: "#5d6b77",
  stTransit: "#c2570f",
  stActive: "#1d7a45",
  stMnt: "#c02626",
  stHold: "#8a95a0",
  ledIdle: "#e8b64c",
  ledReserved: "#8698b0",
  ledTransit: "#f97316",
  ledActive: "#38b06a",
  ledMnt: "#ff6b5e",
  ledHold: "#8a95a0",
  tickUp: "#38e07d",
  tickDown: "#ff6b5e",
  darkCard: "#1c2738",
  darkCardBorder: "#2c3a4e",
  darkCardWell: "#141d2b",
  darkCardChip: "#2c3a4e",
  termBg: "#16202c",
  termBar: "#0f1722",
  termBorder: "#2b3850",
  termBarline: "#223047",
  termText: "#8698b0",
  termCaret: "#38e07d",
  termClose: "#4d5e75",
  docRegistration: "#2f6b4f",
  docCustoms: "#2f4d8a",
  docInsurance: "#4d7d74",
  docInspection: "#6a7fae",
  docReference: "#b9bdc9",
  sand: "#e4e1d8",
  paper: "#faf9f6",
  shopInk: "#1f2d3a",
  shopInk2: "#3a4552",
  shopInk3: "#5b6672",
  shopInk4: "#8a929b",
  shopLine: "#e3e6e9",
  shopLineSoft: "#eceef0",
  shopFill: "#f2f4f5",
  shopOk: "#2f9e5c",
  shopOkSoft: "#e9f7ee",
  shopAmber: "#eda153",
  shopAmberDeep: "#b5761a",
  shopAmberSoft: "#fdf1e0",
  shopField: "#fafbfb",
} as const;

/**
 * The radius scale, as literals, for the same three surfaces.
 *
 * A clipboard card pasted into Gmail carries no stylesheet, so `border-radius: var(--radius-md)`
 * there resolves to nothing and the card renders with square corners. Same reasoning as the colours
 * above; `ds-colors.test.ts` checks these against globals.css too, so the two cannot drift.
 */
export const RADII = {
  sm: "2px",
  md: "4px",
  lg: "6px",
} as const;

/** The CSS custom-property name each key maps to, so the test can check them pair by pair. */
export const CSS_VAR_NAME: Record<keyof typeof COLORS, string> = {
  navyDeep: "--navy-deep",
  navy: "--navy",
  navyMid: "--navy-mid",
  mutedDark: "--muted-dark",
  muted: "--muted",
  mutedLight: "--muted-light",
  borderStrong: "--border-strong",
  border: "--border",
  surface3: "--surface3",
  surface2: "--surface2",
  background: "--background",
  surface: "--surface",
  foreground: "--foreground",
  ink: "--ink",
  inkDeep: "--ink-deep",
  navySoft: "--navy-soft",
  textPrimary: "--text-primary",
  textSecondary: "--text-secondary",
  textTertiary: "--text-tertiary",
  textMuted: "--text-muted",
  textFaint: "--text-faint",
  textOnDark: "--text-on-dark",
  textOnDarkDim: "--text-on-dark-dim",
  desktopBase: "--desktop-base",
  desktopHi: "--desktop-hi",
  surfaceRaised: "--surface-raised",
  surfaceAlt: "--surface-alt",
  chrome: "--chrome",
  chromePress: "--chrome-press",
  chromeDeep: "--chrome-deep",
  neutralBtn: "--neutral-btn",
  neutralBtnHi: "--neutral-btn-hi",
  mapPlate: "--map-plate",
  borderMid: "--border-mid",
  borderHair: "--border-hair",
  borderHair2: "--border-hair2",
  brand: "--brand",
  brandDeep: "--brand-deep",
  brandHover: "--brand-hover",
  brandPress: "--brand-press",
  brandLight: "--brand-light",
  brandPale: "--brand-pale",
  brandSoft: "--brand-soft",
  brandFg: "--brand-fg",
  gold: "--gold",
  ok: "--ok",
  okSoft: "--ok-soft",
  okDeep: "--ok-deep",
  warn: "--warn",
  warnSoft: "--warn-soft",
  warnDeep: "--warn-deep",
  warnBorder: "--warn-border",
  warnAmber: "--warn-amber",
  danger: "--danger",
  dangerSoft: "--danger-soft",
  dangerDeep: "--danger-deep",
  dangerBorder: "--danger-border",
  dangerWash: "--danger-wash",
  dangerHover: "--danger-hover",
  dangerPress: "--danger-press",
  action: "--action",
  info: "--info",
  infoSoft: "--info-soft",
  infoDeep: "--info-deep",
  ai: "--ai",
  aiBg: "--ai-bg",
  neutral: "--neutral",
  neutralBg: "--neutral-bg",
  stIdle: "--st-idle",
  stReserved: "--st-reserved",
  stTransit: "--st-transit",
  stActive: "--st-active",
  stMnt: "--st-mnt",
  stHold: "--st-hold",
  ledIdle: "--led-idle",
  ledReserved: "--led-reserved",
  ledTransit: "--led-transit",
  ledActive: "--led-active",
  ledMnt: "--led-mnt",
  ledHold: "--led-hold",
  tickUp: "--tick-up",
  tickDown: "--tick-down",
  darkCard: "--dark-card",
  darkCardBorder: "--dark-card-border",
  darkCardWell: "--dark-card-well",
  darkCardChip: "--dark-card-chip",
  termBg: "--term-bg",
  termBar: "--term-bar",
  termBorder: "--term-border",
  termBarline: "--term-barline",
  termText: "--term-text",
  termCaret: "--term-caret",
  termClose: "--term-close",
  docRegistration: "--doc-registration",
  docCustoms: "--doc-customs",
  docInsurance: "--doc-insurance",
  docInspection: "--doc-inspection",
  docReference: "--doc-reference",
  sand: "--sand",
  paper: "--paper",
  shopInk: "--shop-ink",
  shopInk2: "--shop-ink-2",
  shopInk3: "--shop-ink-3",
  shopInk4: "--shop-ink-4",
  shopLine: "--shop-line",
  shopLineSoft: "--shop-line-soft",
  shopFill: "--shop-fill",
  shopOk: "--shop-ok",
  shopOkSoft: "--shop-ok-soft",
  shopAmber: "--shop-amber",
  shopAmberDeep: "--shop-amber-deep",
  shopAmberSoft: "--shop-amber-soft",
  shopField: "--shop-field",
};

/**
 * A `:root` block carrying the whole palette, for a standalone document that builds its own
 * stylesheet. Prepend it and every `var(--token)` in that document resolves the way it does in the
 * app, rather than to nothing at all.
 */
export const DS_ROOT_CSS = `:root{${(Object.keys(COLORS) as (keyof typeof COLORS)[])
  .map((k) => `${CSS_VAR_NAME[k]}:${COLORS[k]};`)
  .join("")}}`;
