// Shared reading and writing of the to-do list.
// docs/todo.json is the SOURCE. docs/TODO.md is a generated mirror, for reading in the editor and
// for a readable git diff: never edit it, it is overwritten on every save.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const JSON_PATH = resolve(ROOT, "docs/todo.json");
export const MD_PATH = resolve(ROOT, "docs/TODO.md");

// He TYPES his rank, so any P1 to P9 is his to use. P1 is the most urgent.
export const RANK_RE = /^P[1-9]$/;
export const LABELS = ["web", "app", "test"];

export function emptyList() {
  return { updated: new Date().toISOString(), items: [] };
}

export function readList() {
  if (!existsSync(JSON_PATH)) return emptyList();
  const raw = JSON.parse(readFileSync(JSON_PATH, "utf8"));
  return { updated: raw.updated ?? null, items: Array.isArray(raw.items) ? raw.items.map(clean) : [] };
}

export function clean(item) {
  return {
    id: String(item.id ?? newId()),
    text: String(item.text ?? "").trim(),
    rank: typeof item.rank === "string" && RANK_RE.test(item.rank.toUpperCase()) ? item.rank.toUpperCase() : null,
    labels: Array.isArray(item.labels) ? item.labels.filter((l) => LABELS.includes(l)) : [],
    notes: String(item.notes ?? ""),
    images: Array.isArray(item.images) ? item.images.map(String) : [],
    done: Boolean(item.done),
    doneAt: item.doneAt ? String(item.doneAt) : null,
  };
}

export function newId() {
  return "t" + Math.random().toString(36).slice(2, 9);
}

export function writeList(list) {
  const out = { updated: new Date().toISOString(), items: list.items.map(clean) };
  writeFileSync(JSON_PATH, JSON.stringify(out, null, 2) + "\n", "utf8");
  writeFileSync(MD_PATH, toMarkdown(out), "utf8");
  return out;
}

// The mirror. Same four slots as the board: tick, rank, labels, notes, pictures.
export function toMarkdown(list) {
  const open = list.items.filter((i) => !i.done);
  const done = list.items.filter((i) => i.done);
  const day = (list.updated ?? new Date().toISOString()).slice(0, 10);

  const line = (it) => {
    const rows = [
      `- [${it.done ? "x" : " "}] ${it.rank ?? "P_"} ${it.text}${it.labels.map((l) => " `" + l + "`").join("")}`,
      `      notes:${it.notes ? " " + it.notes.replace(/\s*\n\s*/g, " ") : ""}`,
      ...it.images.map((src) => `      ![](${src})`),
    ];
    return rows.join("\n");
  };

  const block = (items) => items.map(line).join("\n\n");

  return [
    "# To-do",
    "",
    `**${open.length} open · ${done.length} done · last touched ${day}**`,
    "",
    "Generated from `docs/todo.json` by the board. Do not edit this file: open the board instead,",
    "`node scripts/todo-server.mjs`, and everything you tick, rank or type there lands here.",
    "",
    "## Open",
    "",
    open.length ? block(open) : "_Nothing open._",
    "",
    "## Done",
    "",
    done.length ? block(done) : "_Nothing ticked off yet._",
    "",
  ].join("\n");
}

// One-off: read the hand-written markdown list into the JSON shape.
export function fromMarkdown(md) {
  const items = [];
  for (const raw of md.split(/\r?\n/)) {
    const task = /^- \[( |x|X)\] (.*)$/.exec(raw);
    if (task) {
      let body = task[2];
      const rank = /^(P[1-9])_?\s+|^P_\s+/i.exec(body);
      const band = rank && rank[1] ? rank[1].toUpperCase() : null;
      if (rank) body = body.slice(rank[0].length);
      const labels = [];
      body = body.replace(/`([a-z]+)`/g, (m, word) => {
        if (LABELS.includes(word)) { labels.push(word); return ""; }
        return m;
      });
      items.push(clean({
        id: newId(),
        text: body.replace(/\s+·\s*$/, "").trim(),
        rank: band,
        labels,
        done: task[1].toLowerCase() === "x",
      }));
      continue;
    }
    const last = items[items.length - 1];
    if (!last) continue;
    const note = /^\s+notes:\s*(.*)$/.exec(raw);
    if (note) { last.notes = note[1].trim(); continue; }
    const img = /^\s+!\[[^\]]*\]\(([^)]+)\)\s*$/.exec(raw);
    if (img) { last.images.push(img[1]); continue; }
  }
  return { updated: new Date().toISOString(), items };
}
